name: Publish package to GitHub Packages
on:
  push:
    branches:
      - "master"
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      - name: Publish package
        run: mvn --batch-mode --update-snapshots verify -Dmaven.test.skip
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
